.PHONY:	
	    clean
 
clean:
	find -name \*.pyc -delete
	find -name \*.pyo -delete
	find -name __pycache__ -delete
	find -name \*.txt -delete
	find -name \out.rst* -delete
	find -name \*.restart -delete
	find -name \rnd.state -delete
	find -name \*.log -delete
	find -name \mdout.mdp -delete
	find -name \*.tpr -delete
	rm -rf run-initialise/0*
	rm -rf run-25/0*
	rm -rf run-restart/0*
	rm -rf run-restart/initial_path
	rm -rf gromacs_input/pyretis.mdp
 
   
