# -*- coding: utf-8 -*-
"""
This file contains methods used in the TIS method
"""
from __future__ import absolute_import
import numpy as np
from .path import Path, paste_paths, reverse_path
from .montecarlo import metropolis_accept_reject
from .particlefunctions import calculate_kinetic_energy

__all__ = ['make_tis_step', 'generate_initial_path']


MAXLEN = 10000


def make_tis_step(rgen, system, path, order_function, interfaces, integrator,
                  aimless=True, freq=0.5, allowmaxlength=True, start_cond='L'):
    """
    This method will perform a TIS step and generate a new trajectory
    from an existing one, either by performing a time-reversal move or
    by shooting. T(h)is is determined randomly by drawing a random number
    from a uniform distribution.

    Parameters
    ----------
    rgen : object of type RandomGenerator
        This is the random generator that will be used.
    system : object of type System
        System is used here since we need access to the temperature
        and to the particle list.
    path : object of type Path
        This is the input path wich will be used for generating a
        new path.
    order_function : function
        This function takes the system as it's argument and returns a float
        which is equal to the order parameter.
    interfaces : list/tuple of floats
        These are the interface positions on form [left, middle, right]
    aimless : boolean, optional
        Is the shooting aimless or not
    freq : float, in range [0, 1)
        This determines when we shoot/reverse
    allowmaxlength : boolean
        If true, the path generated by shooting may extend to the same
        max-length as the trial path. Typically this is the overall
        max-length set in tis.
    """
    if rgen.rand() < freq:
        #print('Reversing path')
        new_path = reverse_path(path)
        start, _, _ = new_path.check_interfaces(interfaces)
        new_path.generated = 'tr'
        if start == start_cond:
            accept = True
            status = 'ACC'
        else:
            accept = False
            status = 'BWI'  # backward trajectory end at wrong interface
        new_path.status = status

    else:
        #print('Shooting')
        accept, new_path, status = shoot(rgen, system, path, order_function,
                                         interfaces, integrator, aimless,
                                         allowmaxlength=allowmaxlength,
                                         start_cond=start_cond)
        if new_path:  # store some additional data for the shooting move
            #new_path.parent = path
            new_path.generated = 'sh'
    return accept, new_path, status


def shoot(rgen, system, path, order_function, interfaces, integrator,
          aimless, allowmaxlength=False, start_cond='L'):
    """
    Method to perform a shooting-move.

    Parameters
    ----------
    rgen : object of type RandomGenerator
        This is the random generator that will be used.
    system : object of type System
        System is used here since we need access to the temperature
        and to the particle list.
    path : object of type Path
        This is the input path wich will be used for generating a new path.
    order_function : function
        This function takes the system as it's argument and returns a float
        which is equal to the order parameter.
    interfaces : list/tuple of floats
        These are the interface positions on form [left, middle, right]
    aimless : boolean
        Is the shooting aimless or not

    Returns
    -------
    out[0] : boolean
        True if the path can be accepted
    out[1] : object of type Path or None
        Returns the generated Path if something was generated
    out[2] : string
        Status of the path, this is one of the strings defined in
        retis.core.path._STATUS
    """
    accept, trial_path, status = False, None, None  # return values
    # select the shooting point from path at random.
    # (Do not include end-points)
    idx = rgen.random_integers(1, len(path.path) - 2)
    pos, vel, orderp = path.path[idx]  # extract phase point
    system.particles.vel = np.copy(vel)
    system.particles.pos = np.copy(pos)
    system.force()  # update forces
    # kick the timeslice:
    dke = _kick_timeslice(rgen, system, aimless=aimless, momentum=False)
    # update the order paramater since it could depend on velocity
    orderp, _ = order_function(system)
    # We now check if the kick was ok or not:
    # 1) check if the kick was too violent:
    left, _, right = interfaces
    if not left < orderp < right:  # Kicked outside of boundaries!'
        accept, status = False, 'KOB'
        # Note trial_path is here just None
        return accept, trial_path, status
    # 2) If the kick is not aimless, we much check if we reject it or not:
    if not aimless:
        accept_kick = metropolis_accept_reject(rgen, system, dke)
        # here call bias if needed
        # ... Insert call to bias ...
        if not accept_kick:  # Momenta Change Rejection
            accept, status = False, 'MCR'
            # Note trial_path is here just None
            return accept, trial_path, status
    # ok: kick was either aimless or it was accepted by Metropolis
    # we should now generate trajectories, but first check how long
    # it should be:
    if allowmaxlength:
        maxlen = MAXLEN
    else:
        maxlen = int((len(path.path) - 2) / rgen.rand()) + 2
        maxlen = min(maxlen, MAXLEN)
    # since forward path must be at least one step, max for backwards is:
    maxlenb = maxlen - 1
    # generate the backward path:
    path_back, success_back, _ = propagate(system, integrator,
                                           order_function,
                                           interfaces,
                                           maxlen=maxlenb,
                                           reverse=True)
    time_shoot = path.time_origin + idx
    path_back.time_origin = time_shoot
    if not success_back:
        # something went wrong, most probably the path length was exceeded
        accept = False
        status = 'BTL'  # backward trajectory too long (maxlenb "too small")
        if len(path_back.path) == MAXLEN - 1:  # exceeds maximum memory length
            status = 'BTX'
        # Note trial_path is here just None
        return accept, trial_path, status
    # backward seems ok so far, check if the ending point is correct:
    if path_back.get_end_point(left, right) != start_cond:
        # backward trajectory end at wrong interface
        accept, status = False, 'BWI'
        # Note trial_path is here just None
        return accept, trial_path, status
    # everything seems fine, propagate forward
    maxlenf = maxlen - len(path_back.path) + 1
    path_forw, success_forw, _ = propagate(system,
                                           integrator,
                                           order_function,
                                           interfaces,
                                           maxlen=maxlenf,
                                           reverse=False)
    path_forw.time_origin = time_shoot
    # now, the forward could have failed by exceeding maxlenf
    # however, it could also fail when we paste together so that
    # the length is larger than the allowed maximum, we paste first
    # and ask later:
    trial_path = paste_paths(path_back, path_forw, overlap=True, maxlen=MAXLEN)
    if not success_forw:
        accept = False
        status = 'FTL'
        if len(trial_path.path) == MAXLEN:  # exceeds "memory"
            status = 'FTX'
        # trial_path is now different from None, set status:
        trial_path.status = status
        return accept, trial_path, status
    # we have made it so far, check if we cross middle interface
    # finally, check if middle interface was crossed:
    _, _, cross = trial_path.check_interfaces(interfaces)
    if not cross[1]:  # not crossed middle
        accept, status = False, 'NCR'
    else:
        accept, status = True, 'ACC'
    trial_path.status = status
    return accept, trial_path, status


def generate_initial_path(system, interfaces, integrator, rgen,
                          order_function, start_cond='L'):
    """
    Simple method to generate an initial path
    This method will generate an initial path by repeatedly
    kicking a phase-space point until the middle interface is crossed.
    The point before and after kicking are stored, so when the
    middle interface is crossed we have two points we can integrate
    forward and backward in time.

    Parameters
    ----------
    system : object of type System
        This is the system that contains the particles we are investigating
    interfaces : list of floats
        These are the interface positions on form [left, middle, right]
    integrator : object of type Integrator
        This is the propagator of the simulation
    rgen : object of type RandomGenerator
        This is the random generator that will be used.
    order_function : function
        This is a function that calculates the order parameter for a
        system.
    start_cond : string, optional
        This gives the start condition. This will typically
        be interface[0]

    Returns
    -------
    out : object of type Path
        This is the generated initial path
    """
    _, middle, _ = interfaces
    previous, _ = _kick_across_middle(system, integrator,
                                      rgen, order_function, middle)
    # note: current point is stored in system
    # Loop is done, we have two points (previous and the
    # current system.particles)
    # we can propagate current phase point forward:
    path_forw, success, msg = propagate(system, integrator, order_function,
                                        interfaces, maxlen=MAXLEN)
    if not success:
        raise ValueError('Forward path not successfull.', msg)
    # and previous pase point backward.
    # First we set system to be at this point:
    system.particles.set_phase_point(previous)
    # then propagate :-)
    path_back, success, msg = propagate(system, integrator, order_function,
                                        interfaces, maxlen=MAXLEN,
                                        reverse=True)
    if not success:
        raise ValueError('Backward path not successfull.', msg)
    # Merge backward and forward, here we do not set maxlen since
    # both backward and forward may have this length
    initial_path = paste_paths(path_back, path_forw, overlap=False)
    if len(initial_path.path) == MAXLEN:
        raise ValueError('Initial path too long len(path) >= NX')
    start, end, _ = initial_path.check_interfaces(interfaces)
    # ok, now its time to check the path:
    # 0) We can start at the starting condition, pass the middle
    # and continue all the way to the end - perfect!
    # 1) we can start at the starting condition, pass the middle
    # and return to starting condition - this is perfecly fine
    # 2) We can start at the wrong interface, pass the middle and
    # end at the same (wrong) interface - we now need to do some shooting moves
    # 3) We can start at wrong interface and end and the starting condition
    # we just have to reverse the path then.
    if start == start_cond:  # case 0 and 1
        initial_path.status = 'ACC'
        return initial_path
    # Now we do the other cases:
    if end == start_cond:  # case 3 (and start != start_cond)
        #print('Initial path is in the wrong direction: Reversing it!')
        initial_path = reverse_path(initial_path)
        initial_path.status = 'ACC'
    elif end == start:  # case 2
        #print('Initial path start & end at wrong interface')
        #print('Running TIS to fix initial path:')
        initial_path = fix_path_by_tis(system, interfaces, integrator,
                                       rgen, order_function,
                                       initial_path, start_cond)
    else:
        raise ValueError('Could not generate initial path')
    return initial_path


def _kick_across_middle(system, integrator, rgen, order_function, middle):
    """
    This method will repeatadely kick a phase point so that it crosses
    the middle interface.

    Parameters
    ----------
    system : object of type System
        This is the system that contains the particles we are investigating
    integrator : object of type Integrator
        This is the propagator of the simulation
    rgen : object of type RandomGenerator
        This is the random generator that will be used.
    order_function : function
        This is a function that calculates the order parameter for a
        system.
    middle : float
        This is the value for the middle interface.

    Returns
    -------
    out[0] : dict
        This dict contains the pase-point just before the interface.
        It is obtained by calling the ``get_phase_point()`` of the particles
        object.
    out[1] :
        This dict contains the pase-point just after the interface.
        It is obtained by calling the ``get_phase_point()`` of the particles
        object.

    Note
    ----
    This function will update the system state so that the
    system.particles.get_phase_point() == out[1]. This is more convenient
    for the following usage in the ``generate_initial_path`` method.
    """
    # first we search for crossing with the middle interface
    # this is done by sequentially kicking the initial phase point
    particles = system.particles
    curr, _ = order_function(system)
    while True:
        # save current state:
        previous = particles.get_phase_point()
        previous['order'] = curr
        # kick the time slice
        _kick_timeslice(rgen, system, aimless=True, momentum=True)
        # integrate forward one step:
        integrator.integration_step(system)
        # compare previous order parameter and the new one:
        prev = curr
        curr, _ = order_function(system)
        if (prev <= middle < curr) or (curr < middle <= prev):
            # have crossed middle interface, just stop the loop
            break
        elif (prev <= curr < middle) or (middle < curr <= prev):
            # are getting closer, keep the new point
            pass
        else:  # we did not get closer, fall back to previous point
            particles.set_phase_point(previous)
            curr = previous['order']
    return previous, particles.get_phase_point()


def _kick_timeslice(rgen, system, sigma_v=None, aimless=True, momentum=False):
    """
    This method will make a random modification to a time slice.
    It will only modify the velocities.

    Parameters
    ----------
    rgen : object of type RandomGenerator
        This is the random generator that will be used.
    system : object of type system
        System is used here since we need access to the temperature
        and to the particle list
    aimless : boolean, optional
        Determines if we should do aimless shooting or not
    momentum : boolean, optional
        This handles resetting of the momentum

    Returns
    -------
    out : float
        The change in the kinetic energy
    """
    # NOTE: kin_old might be set/optained differently according to
    # the dynamics. E.g. In NVE it is just E-Epot.
    particles = system.particles
    kin_old = calculate_kinetic_energy(particles)
    if aimless:
        vel, _ = rgen.draw_maxwellian_velocities(system)
        particles.vel = vel
    else:  # soft velocity change, add from Gaussian dist
        dvel, _ = rgen.draw_maxwellian_velocities(system, sigma_v=sigma_v)
        particles.vel = particles.vel + dvel
    if momentum:
        pass
    kin_new = calculate_kinetic_energy(particles)
    # NOTE velocity should for some dynamics be rescaled
    dek = kin_new[0] - kin_old[0]
    return dek


def propagate(system, integrator, order_function, interfaces,
              maxlen=None, reverse=False):
    """
    This function will propagate a system in time. During the propagation,
    the system will be modified. However, at the end, the positions, velocities
    and forces will be reset to the initial state.

    Parameters
    ----------
    system : object of type System
        The system object given is assumed to be defined with the correct
        particle list for the system to be propagated. It is also assumed
        to contain the force field.
    integrator : object of type Integrator
        The integrator will be used to propagate the system. It is assumed
        to be correctly set up for the system under consideration.
    order_function : function
        This function takes the system as it's argument and returns a float
        which is equal to the order parameter.
    interfaces : list/tuple of floats
        These are the interface positions on form [left, middle, right]
    maxlen : float
        The maximum length of the path
    reverse : boolean
        If True, the system will be propagated backwards in time

    Returns
    -------
    out[0] : object of type Path
        The generated path from integrating the system in time
    out[1] : boolean
        False if something in propagate went wrong. This is described
        in out[2].
    out[2] : string
        Human representation of the result.
    """
    # first we store the initial pos, vel and forces for the system:
    initial_system = system.particles.get_phase_point()
    left, _, right = interfaces
    new_path = Path(maxlen=maxlen)
    status = 'Empty path'
    while True:
        orderp, _ = order_function(system)
        add = new_path.append(system.particles.pos, system.particles.vel,
                              orderp)
        if not add:
            if len(new_path.path) >= new_path.maxlen:
                status = 'Max. path length exceeded'
            else:
                status = 'Could not add for unknown reason'
            success = False
            break
        if new_path.ordermin[0] < left:
            status = 'Crossed left interface!'
            success = True
            break
        elif new_path.ordermax[0] > right:
            status = 'Crossed right interface!'
            success = True
            break
        if reverse:
            system.particles.vel = -1.0 * system.particles.vel
            # np.negative()
            integrator(system)
            system.particles.vel = -1.0 * system.particles.vel
            # np.negative()
        else:
            integrator(system)
    # reset the system to initial state
    system.particles.set_phase_point(initial_system)
    return new_path, success, status


def fix_path_by_tis(system, interfaces, integrator, rgen, order_function,
                    initial_path, start_cond):
    """
    This method fix a path that starts and ends at the wrong interfaces.
    This is used in connection with the initialization.

    Parameters
    ----------
    system : object of type System
        This is the system that contains the particles we are investigating
    interfaces : list of floats
        These are the interface positions on form [left, middle, right]
    integrator : object of type Integrator
        This is the propagator of the simulation
    rgen : object of type RandomGenerator
        This is the random generator that will be used.
    order_function : function
        This is a function that calculates the order parameter for a
        system.
    initial_path : object of type path
        This is the initial path to fix. It starts & ends at the
        wrong interface.

    Returns
    -------
    out : object of type Path
        The amended path
    """
    left, middle, right = interfaces
    path_ok = False
    while not path_ok:
        accept, trial, _ = make_tis_step(rgen, system,
                                         initial_path,
                                         order_function,
                                         interfaces,
                                         integrator,
                                         allowmaxlength=True,
                                         aimless=True, freq=0.5,
                                         start_cond=start_cond)
        if accept:
            if start_cond == 'R':  # if new path is better, use it:
                better = trial.ordermax[0] > initial_path.ordermax[0]
                better = better and trial.ordermin[0] < middle
                if better:
                    initial_path = trial
                path_ok = initial_path.ordermax[0] > right
            elif start_cond == 'L':  # if new path is better, use it:
                better = trial.ordermin[0] < initial_path.ordermin[0]
                better = better and trial.ordermax[0] > middle
                if better:
                    initial_path = trial
                path_ok = initial_path.ordermin[0] < left
            else:
                raise ValueError('Unknown start_cond')
    initial_path.status = 'ACC'
    return initial_path
