.PHONY:	
	clean
 
clean:
	find -name \*.pyc -delete
	find -name \*.pyo -delete
	find -name __pycache__ -delete
	find -name EXIT -delete
	find -name \*.txt -delete
	find -name \*out.rst* -delete
	find -name \*.restart -delete
	find -name \*.log* -delete
	find -name \*.xvg* -delete
	find -name \*.edr* -delete
	find -name \*.cpt* -delete
	find -name \*.xtc* -delete
	find -name \*.trr* -delete
	find -name \*mdout.mdp* -delete
	find -name \*pyretis.mdp* -delete
	find -name \*.tpr* -delete
	-rm gromacs-run.rst
	-rm conf.g96
	-rm *pyretis-gmx*
	-rm *gromacs-run*
