.PHONY:	
	clean
 
clean:
	find -name \*.pyc -delete
	find -name \*.pyo -delete
	find -name __pycache__ -delete
	find -name EXIT -delete
	find -name \*.log -delete
	-rm -rf run-backward
	-rm -rf run-forward
	-rm -rf run-forward1
	-rm -rf run-forward2
	-rm -rf run-forward3
