image: "python:3.5"

before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip install --upgrade pip
  - pip install coverage
  - pip install -r requirements.txt
  - pip install pep8
  - pip install pylint
  - pip install -e .

test:
  script:
  - pip install coverage
  - coverage run -m unittest discover -s test
  - coverage report -m
  coverage: '/^TOTAL.*\s+(\d+\%)/'

pep8:
  script:
  - pip install pep8
  - pep8 --filename=*.py --count --statistics --exclude=./docs

job-pylint:
  script:
  - pylint pyretis
  allow_failure: true
