site_name: pyretis
pages:
# Introduction
- ['index.md', 'Home']
# User Guide
- ['user-guide/getting-started.md', 'User Guide', 'Getting started']
- ['examples/examples.md', 'Examples', 'Overview']
- ['examples/examples-mc.md', 'Examples', 'Monte Carlo']
- ['examples/examples-md.md', 'Examples', 'Molecular Dynamics']
# About
- ['about/license.md', 'About', 'License']
- ['about/release-notes.md', 'About', 'Release Notes']
theme: readthedocs
# remove the next line for production
use_directory_urls: false
