settings = {'beta': 14.285714285714285,
            'dim': 1,
            'steps': 10000000,
            'generate-vel': {'distribution': 'maxwell',
                             'momentum': False,
                             'seed': 0},
            'integrator': {'gamma': 0.3,
                           'high-friction': False,
                           'name': 'Langevin',
                           'seed': 0,
                           'timestep': 0.002},
            'interfaces': [-0.9,
                           -0.8,
                           -0.7,
                           -0.6,
                           -0.5,
                           -0.4,
                           -0.3,
                           1.0],
            'npart': 1,
            'output': [{'filename': 'traj.gro',
                        'format': 'gro',
                        'header': 'MD FLUX simulation. Step: {}',
                        'target': 'file',
                        'type': 'traj',
                        'when': {'every': 100}}],
            'periodic_boundary': [False],
            'temperature': 0.07,
            'type': 'md-flux',
            'units': 'lj'}
