# -*- coding: utf-8 -*-
"""Classes and methods for paths and path ensembles.

The classes and methods defined in this module are useful for representing
paths and path ensembles.

Important classes and functions
-------------------------------

- Path: Class for defining paths.

- PathEnsemble: Class for defining path ensembles.

- paste_paths: Method for joining two paths, one is in a backward time
  direction and the other is in the forward time direction.

- reverse_path: Method for reversing a path.

- create_path_ensembles: Method for creating a set of `PathEnsemble` objects
  given locations of interfaces defining the path ensembles.
"""
import numpy as np
import warnings
import itertools

__all__ = ['Path', 'PathEnsemble', 'paste_paths', 'reverse_path',
           'create_path_ensembles']

# the following defines a human-readable form of the possible path status:
_STATUS = {'ACC': 'The path has been accepted',
           'MCR': 'Momenta change rejection',
           'BWI': 'Backward trajectory end at wrong interface',
           'BTL': 'Backward trajectory too long (detailed balance condition)',
           'BTX': 'Backward trajectory too long (max-path exceeded)',
           'KOB': 'Kicked outside of boundaries',
           'FTL': 'Forward trajectory too long (detailed balance condition)',
           'FTX': 'Forward trajectory too long (max-path exceeded)',
           'NCR': 'No crossing with middle interface'}

_GENERATED = {'sh': 'Path was generated with a shooting move',
              'tr': 'Path was generated with a time-reversal move',
              'ki': 'Path was generated by integration after kicking',
              's+': 'Path was generated by a swapping move from +',
              's-': 'Path was generated by a Swapping move from -',
              '00': 'Path was generated by a null move'}


def paste_paths(path_back, path_forw, overlap=True, maxlen=None):
    """Merge a backward and a forward path.

    Merge two paths: one is in the backward and the other in the forward
    time direction.

    The resulting path is equal to the two paths stacked in correct time.
    Note that the ordering is important here:
    ``paste_paths(path1, path2) != paste_paths(path2, path1)``.

    The code is very similar to `Path.__add__` but we have to take care:

    - `path_back` must be iterated in reverse (it is assumed to be a
      backward trajectory).
    - we may have to remove one point in `path2` (if the paths overlap).

    Parameters
    ----------
    path_back : object like `Path`
        This is the backward trajectory.
    path_forw : object like `Path`
        This is the forward trajectory.
    overlap : boolean, default is True
        If true, `path_back` and `path_forw` have a common starting-point,
        that is, the first point in `path_forw` is identical to the first point
        in `path_back`. In time-space this means that the first point in
        `path_forw` is identical to the last point in path_back (the backward
        and forward path started at the same location in space).
    maxlen : float, optional
        This is the maximum length for the new path. If it's not given, it will
        just be set to the largest of the `maxlen` of the two given paths.

    Note
    ----
    Some information about the path will not be set here. This must be set
    elsewhere. This includes how the path was generated (`path.generated`)
    and the status of the path (`path.status`).
    """
    if maxlen is None:
        if path_back.maxlen == path_forw.maxlen:
            # everything is ok, they have the same maximum length
            maxlen = path_back.maxlen
        else:
            # They are unequal and both is not None, just pick the largest.
            # In case one is None, the other will be picked.
            # Note that now there is a chance of truncating the path while
            # pasting!
            maxlen = max(path_back.maxlen, path_forw.maxlen)
            msg = 'Unequal maxlen - setting equal to {}'.format(maxlen)
            warnings.warn(msg)
    time_origin = path_back.time_origin - len(path_back.path) + 1
    new_path = Path(maxlen=maxlen, time_origin=time_origin)
    iter_path_back = reversed(path_back.path)  # iterate in correct time dir
    if overlap:  # do not include the overlapping point:
        iter_path_forw = path_forw.path[1:]
    else:
        iter_path_forw = path_forw.path

    for phasepoint in itertools.chain(iter_path_back, iter_path_forw):
        app = new_path.append(*phasepoint)
        if not app:
            msg = 'Truncated path at: {}'.format(len(new_path.path))
            warnings.warn(msg)
            return new_path
    return new_path


def reverse_path(path, order_func=None):
    """Reverse a path and return the reverse path as a new `Path` object.

    This will simply reverse a path and return the reversed path as a new
    `Path` object. An `order_func` can be specified here if we have to
    recalculate the order parameter - this is only done if the `order_func` is
    actually given.

    Parameters
    ----------
    path : object like `Path`
        This is the path we wish to reverse
    order_func : function, optional
        In case the order parameter should be re-calculated for the reverse
        path, the function order_func can be specified to do this.
    """
    new_path = Path(maxlen=path.maxlen)
    for phasepoint in reversed(path.path):
        pos, vel = phasepoint[0], -1.0 * phasepoint[1]
        energy = phasepoint[3]
        if order_func:
            orderp = order_func(pos, vel)
        else:
            orderp = phasepoint[2]
        app = new_path.append(pos, vel, orderp, energy)
        if not app:
            msg = 'Could not reverse path'
            warnings.warn(msg)
    return new_path


def check_crossing(cycle, system, order_function, interfaces,
                   leftside_prev=None):
    """Check if we have crossed an interface during the last step.

    This method is useful for checking if an interface was crossed from
    the previous step till the curent one. This is for instance used in the
    MD simulations for the initial flux.
    If will use a variable to store the previous positions with respect to
    the interfaces and check if interfaces were crossed here.

    Parameters
    ----------
    cycle : int
        This is the current simulation cycle number.
    system : object like `System` from `pyretis.core.system`
        This is the system which defines the phase point we are currently
        investigating.
    order_function : function or object like `OrderParameter` or float.
        `OrderParameter` is defined in `pyretis.core.orderparameter`.
        `order_function` is assumed to be a function accepting
        `system` as a parameter and returning at least two scalars.
        In case a single float is given, the order parameter will not be
        recalculated and this float will just be used as the current order
        parameter.
    interfaces : list of floats
        These are the interfaces to check.
    leftside_prev : list of booleans
        These are used to store the previous positions with respect
        to the interfaces.

    Returns
    -------
    leftside_curr : list of booleans
        These are the updated positions with respect to the interfaces.
    cross : list of tuples
        If a certain interface is crossed, a tuple will be added to this
        list. The tuple is of form (cycle number, interface number, direction)
        where direction is '-' for a crossing in the negative direction and
        '+' for a crossing in the positive direction.
    """
    try:
        orderp = order_function(system)[0]
    except TypeError:
        # Assume TypeError is caused by order_function = a float
        orderp = order_function
    cross = []
    if leftside_prev is None:
        leftside_curr = [orderp < interf for interf in interfaces]
    else:
        leftside_curr = [i for i in leftside_prev]
        for i, (left, interf) in enumerate(zip(leftside_prev, interfaces)):
            if left and orderp > interf:
                leftside_curr[i] = False
                cross.append((cycle, i, '+'))
            elif not left and orderp < interf:
                leftside_curr[i] = True
                cross.append((cycle, i, '-'))
    return leftside_curr, cross


class Path(object):
    """Path(object) - representation of paths.

    This class represents a path. A path consist of a series of consecutive
    snapshots (the trajectory) with the corresponding order parameter.
    We assume here that the order parameter is a scalar value.

    Attributes
    ----------
    maxlen : int
        This is the maximum path length. Some algorithms requires this to
        be set. Others don't, which is indicated by setting `maxlen` equal to
        None.
    path : list
        This is the trajectory/series of snapshots, stored as a list of tuples.
        Each tuple stores (positions, velocities, order parameters, energy).
    ordermin : tuple
        This is the (current) minimum order parameter for the path.
        `ordermin[0]` is the value, `ordermin[1]` is the index in `self.path`.
    ordermax : tuple
        This is the (current) maximum order parameter for the path.
        `ordermax[0]` is the value, `ordermax[1]` is the index in `self.path`.
    time_origin : int
        This is the location of the phase point `path[0]` relative to its
        parent. This might be useful for plotting.
    status : str or None
        The status of the path. The possibilities are defined
        in the variable `_STATUS`
    generated : tuple
        This contains information on how the path was generated.
        `generated[0]` : string, as defined in the variable `_GENERATED`
        `generated[1:]` : additional information:
        For ``generated[0] == 'sh'`` the additional information is the index
        of the shooting point on the old path, the new path and the
        corresponding order parameter.
    """

    def __init__(self, maxlen=None, time_origin=0):
        """Initialize the Path object.

        Parameters
        ----------
        maxlen : int, optional
            This is the max-length of the path. The default value,
            None, is just a path of arbitrary length.
        time_origin : int, optional
            This can be used to store the shooting point of a parent
            trajectory.
        """
        self.maxlen = maxlen
        self.path = []
        self.ordermin = None
        self.ordermax = None
        self.time_origin = time_origin
        self.status = None
        self.generated = None

    def __iter__(self):
        """Iterate over the phase-space points.

        Yields
        ------
        out : tuple
            The phase-space points will be yielded.
        """
        for phasepoint in self.path:
            yield phasepoint

    def append(self, pos, vel, orderp, energy):
        """Append a new phase point to the path.

        We will here append a new phase space point to the path.
        The phase point is assumed to be given by positions and velocities
        with a corresponding scalar order parameter and energy.

        Parameters
        ----------
        pos : numpy.array
            The positions of the particles,
        vel: numpy.array
            The velocities of the particles,
        orderp : list of floats
            This variable is the order parameter for the given point.
            `orderp[0]` is the actual order parameter used in path sampling
            methods while `orderp[1:]` can represent other order parameters
            for instance is `orderp[1]` typically the velocity of `orderp[0]`.
        """
        if self.maxlen is None or len(self.path) < self.maxlen:
            self.path.append([np.copy(pos), np.copy(vel), orderp, energy])
            self._update_orderp(orderp[0], len(self.path) - 1)
            return True
        else:
            msg = 'Path length exceeded! Could not append to path!'
            warnings.warn(msg)
            return False

    def _update_orderp(self, orderp, idx):
        """Update current min/max order parameter.

        Update the min/max order parameter given a new order parameter. It
        will just check if the given order parameter is larger or smaller than
        the current ones.

        Parameters
        -----------
        orderp : float
            This is the new order parameter.
        idx : integer
            This is the index of the new order parameter in `self.path`.
        """
        if self.ordermax is None or orderp > self.ordermax[0]:
            self.ordermax = (orderp, idx)
        if self.ordermin is None or orderp < self.ordermin[0]:
            self.ordermin = (orderp, idx)

    def get_min_max_orderp(self):
        """Get the minimum and maximum order parameter on the path.

        Update the minimum and maximum order parameter on the path and
        return them. This function will explicitly loop over the path,
        check all phase space points and find the minimum and maximum order
        parameter.

        Returns
        -------
        out[0] : list
            This is the minimum order parameter, tuple with (value, index)
        out[1] : list
            This is the maximum order parameter, tuple with (value, index)
        """
        ordermin = None
        ordermax = None
        for i, phasepoint in enumerate(self.path):
            orderp = phasepoint[2][0]
            if ordermin is None or ordermax is None:
                ordermin = (orderp, i)
                ordermax = (orderp, i)
            else:
                if orderp > ordermax[0]:
                    ordermax = (orderp, i)
                if orderp < ordermin[0]:
                    ordermin = (orderp, i)
        self.ordermin = ordermin
        self.ordermax = ordermax
        return ordermin, ordermax

    def check_interfaces(self, interfaces):
        """Check current status of the path.

        Get the current status of the path with respect to the `interfaces`.
        This is intended to determine if we have crossed certain interfaces or
        not.

        Parameters
        ----------
        interfaces : list of floats
            This list is assumed to contain the three interface values
            left, middle and right

        Returns
        -------
        out[0] : str, 'L' or 'R' or None
            Start condition: did the trajectory start at the left ('L') or
            right (R) interface.
        out[1] : str, 'L' or 'R' or None
            Ending condition: did the trajectory end at the left ('L') or
            righ ('R') interface or None of them.
        out[2] str, 'M' or '*'
            'M' if middle interface is crossed, '*' otherwise.
        out[3] : list of boolean
            out[2][i] = True if ordermin < interfaces[i] <= ordermax
        """
        start, end, middle, cross = None, None, None, None
        if len(self.path) < 1:
            warnings.warn('Path is empty!')
            return start, end, middle, cross
        ordermax, ordermin = self.ordermax[0], self.ordermin[0]
        cross = [ordermin < interpos <= ordermax for interpos in interfaces]
        left, right = min(interfaces), max(interfaces)
        # check end & start:
        end = self.get_end_point(left, right)
        start = self.get_start_point(left, right)
        middle = 'M' if cross[1] else '*'
        return start, end, middle, cross

    def get_end_point(self, left, right):
        """Return the end point of the path as a string.

        The end point is either to the left of the `left` interface or to
        the right of the `right` interface, or somewhere in between.

        Parameters
        ----------
        left : float
            The left interface
        right : float
            The right interface

        Returns
        -------
        out : string
            String representing where the end point is ('L' - left,
            'R' - right or None).
        """
        if self.path[-1][2][0] < left:
            end = 'L'
        elif self.path[-1][2][0] > right:
            end = 'R'
        else:
            end = None
        return end

    def get_start_point(self, left, right):
        """
        Return the start point of the path as a string.

        The start point is either to the left of the `left` interface or to
        the right of the `right` interface.

        Parameters
        ----------
        left : float
            The left interface
        right : float
            The right interface

        Returns
        -------
        out : string
            String representing where the start point is ('L' - left,
            'R' - right or None).
        """
        if self.path[0][2][0] <= left:
            start = 'L'
        elif self.path[0][2][0] >= right:
            start = 'R'
        else:
            start = None
            warnings.warn('Undefined starting point')
        return start

    def get_path_data(self, status, interfaces):
        """
        Return information about the Path.

        This information can (and is typically) stored in a `PathEnsemble`.

        Parameters
        ----------
        status : string
            This represents the current status of the path.
        interfaces : list
            These are just the interfaces we are currently considering.
        """
        path_info = {}
        path_info['generated'] = self.generated
        path_info['status'] = status
        path_info['length'] = len(self.path)

        if self.ordermax is not None:
            path_info['ordermax'] = tuple(self.ordermax)
        else:
            path_info['ordermax'] = (0.0, 0)

        if self.ordermin is not None:
            path_info['ordermin'] = tuple(self.ordermin)
        else:
            path_info['ordermin'] = (0.0, 0)

        start, end, middle, _ = self.check_interfaces(interfaces)
        path_info['interface'] = (start, middle, end)
        return path_info

    def set_move(self, move):
        """Update the path move.

        The path move is a short string that represent how the path
        was generated. It should preferably match one of the moves defined
        in `_GENERATED`

        Parameters
        ----------
        move : string
            A short description of the move
        """
        if self.generated is None:
            self.generated = (move, 0, 0, 0)
        else:
            self.generated = (move, self.generated[1], self.generated[2],
                              self.generated[3])

    def success(self, idetect):
        """
        Check if the path is successful.

        The check is based on the maximum order parameter and the value of
        `idetect`. It is successful if the maximum order parameter is greater
        than `idetect`.

        Parameters
        ----------
        idetect : float
            The value for which the path is successfull
        """
        return self.ordermax[0] > idetect

    def __add__(self, other):
        """
        Define how we add two paths, i.e.: ``new_path = self + other``.

        Parameters
        ----------
        self, other : objects of type like `Path`

        Returns
        -------
        out : object of type `Path`
            The Path obtained as ``out = self + other``.
        """
        if self.maxlen == other.maxlen:
            # everything is ok, they have the same length
            maxlen = self.maxlen
        else:
            # they are unequal and both is not none, just pick the largest
            maxlen = max(self.maxlen, other.maxlen)
            msg = 'Unequal maxlen - setting equal to {}'.format(maxlen)
            warnings.warn(msg)

        new_path = Path(maxlen=maxlen)

        for phasepoint in itertools.chain(self.path, other.path):
            app = new_path.append(*phasepoint)
            if not app:
                msg = 'Truncated path at: {}'.format(len(new_path.path))
                warnings.warn(msg)
                return new_path
        return new_path

    def __iadd__(self, other):
        """
        Add path data to a path from another path, i.e.: ``self += other``.

        This will simply append the phasepoints from `other`.

        Parameters
        ----------
        other : object of type `Path`
            The object to add path data from.

        Returns
        -------
        self : object of type `Path`
            The updated path object.
        """
        for phasepoint in other.path:
            app = self.append(*phasepoint)
            if not app:
                msg = 'Truncated path at: {}'.format(len(self.path))
                warnings.warn(msg)
                return self
        return self

    def __str__(self):
        """Return a simple string representation of the Path."""
        msg = ['Path with length {} (max: {})'.format(len(self.path),
                                                      self.maxlen)]
        msg += ['\tOrder parameter max: {}'.format(self.ordermax)]
        msg += ['\tOrder parameter min: {}'.format(self.ordermin)]
        if len(self.path) > 0:
            msg += ['\tStart {}'.format(self.path[0][2][0])]
            msg += ['\tEnd {}'.format(self.path[-1][2][0])]
        if self.status:
            msg += ['\tStatus: {}'.format(_STATUS[self.status])]
        if self.generated:
            msg += ['\tGenerated: {}'.format(_GENERATED[self.generated[0]])]
        return '\n'.join(msg)


class PathEnsemble(object):
    """PathEnsemble(object) - representation of a path ensemble.

    This class represents a collection of `Paths` in a path ensemble.
    In general paths may be 'long and complicated' so here, we really
    just store an simplified abstraction of the path, which is obtained by the
    `Path.get_path_data()` method for a given `Path` object. The returned
    dictionary is stored in the list `PathEnsemble.paths`. The only path we
    store, is the last accepted path. This is convenient for the RETIS method
    where paths may be swapped between path ensembles.

    Attributes
    ----------
    ensemble : str
        This is a string representation of the path ensemble. This is used to
        identify the ensemble in retis simulations and the string should be
        one of ``[0^-]``, ``[0^+]``, ``[1^+]``, ...
    interfaces : list of floats
        Interfaces, specified with the values for the
        order parameters: `[left, middle, right]`.
    detect : float
        Interface to use for analysis.
    paths : list
        This list contains the stored information for the paths. Here
        we only store the data returned by calling the `get_path_data()`
        method of the `Path` object.
    nstats : dict of ints
        This dict store some statistics for the path ensemble. The keys are

        - `npath` : The number of paths stored.
        - `nshoot` : The number of accepted paths generated by shooting.
        - `ACC`, `BWI`, ... : Number of paths with given status
          (from `_STATUS`).
    maxpath : int
        The maximum number of paths to store.
    last_path : object like `pyretis.core.Path`
        This is the last **accepted** path.
    """

    def __init__(self, ensemble, interfaces, detect=None, maxpath=10000000):
        """
        Initialize the PathEnsemble object.

        Parameters
        ----------
        ensemble : string
            The string representation of the path ensemble.
        interfaces : list of ints
            These are the interfaces specified with the values
            for the order parameters: [left, middle, right]
        """
        self.ensemble = ensemble
        self.interfaces = tuple(interfaces)  # Should not change interfaces
        self.detect = detect  # detect interface to use for analysis
        self.last_path = None
        self.nstats = {'npath': 0, 'nshoot': 0, 'ACC': 0}
        self.paths = []
        self.maxpath = maxpath

    def reset_data(self):
        """
        Erase the stored data in the path ensemble.

        It can be used in combination with flushing the data to a
        file in order to periodically write and empty the amount of data
        stored in memory.

        Notes
        -----
        We do not reset `self.last_path` as this might be used in the
        RETIS method.
        """
        self.paths = []
        for key in self.nstats:
            self.nstats[key] = 0

    def add_path_data(self, path, status, cycle=0):
        """Append data from the given path to `self.path_data`.

        This will add the data from a given` path` to the list path data
        for this ensemble. If will also update `self.last_path` if the given
        `path` is accepted.

        Parameters
        ----------
        path : object like `Path`
            This is the object to store data from.
        status : string
            This is the status of the path. Note that the path object also
            have a status property. However this one might not be set, for
            instance when path is just None. We therefore use `status` here
            as a parameter.
        cycle : int, optional
            The current cycle number
        """
        if len(self.paths) >= self.maxpath:
            msg = ['Maxpath in ensemble {} exceeded!'.format(self.ensemble)]
            msg += ['Emptying path-data in this path ensemble!']
            msg += ['Note that this might influence the analysis if']
            msg += ['you run it using this path ensemble object.']
            msg += ['(Hint: Use the path ensemble file for the analysis.)']
            warnings.warn('\n'.join(msg))
            self.paths = []
        # update statistics:
        if path is None:
            # Here we add a dummy path with minimal info. This is because we
            # could not generate a path for some reason which should be
            # specified by the status.
            path_data = {'status': status, 'generated': ('', 0, 0, 0)}
        else:
            path_data = path.get_path_data(status, self.interfaces)
            if path_data['status'] == 'ACC':  # store the path
                self.last_path = path
                if path_data['generated'][0] == 'sh':
                    self.nstats['nshoot'] += 1
        path_data['cycle'] = cycle  # also store cycle number
        self.paths.append(path_data)  # store the new data
        # update some statistics:
        try:
            self.nstats[status] += 1
        except KeyError:  # this is the first occurence of the status:
            self.nstats[status] = 1
        self.nstats['npath'] += 1

    def get_accepted(self):
        """Yield accepted paths from the PathEnsemble.

        This method will give an iterator useful for iterating over
        accepted paths only. In the PathEnsemble we store both accepted
        and rejected paths. This method will loop over all paths stored
        and yield the accepted paths the correct number of times.
        """
        last_path = None
        for path in self.paths:
            if path['status'] == 'ACC':
                last_path = path
            yield last_path

    def get_acceptance_rate(self):
        """Return acceptance rate for the path ensemble.

        The acceptance rate is obtained as the fraction of accepted paths to
        the total number of paths in the path ensemble. This will only
        consider the paths that are currently stored in self.paths.

        Returns
        -------
        out : float
            The acceptance rate.
        """
        acc = 0
        npath = 0
        for path in self.paths:
            if path['status'] == 'ACC':
                acc += 1
            npath += 1
        return float(acc) / float(npath)

    def get_paths(self):
        """Yield the different paths stored in the path ensemble.

        It is included here in order to have a simple compatibility between
        the `PathEnsemble` object and the `PathEnsembleFile` object defined in
        `pyretis.inout`. This is useful for the analysis.

        Yields
        ------
        out : dict
            This is the dictionary representing the path data.
        """
        for path in self.paths:
            yield path

    def get_start_condition(self):
        """Return the appropriate start condition for an ensemble.

        This is useful for RETIS simulations where we for one ensemble
        need to start to the left.

        Returns
        -------
        out : string
            'R' for right or 'L' for left start condition.
        """
        if self.ensemble == '[0^-]':
            return 'R'
        else:
            return 'L'

    def __str__(self):
        """Return a string with some info about this object."""
        msg = ['Path ensemble: {}'.format(self.ensemble)]
        msg += ['\tInterfaces: {}'.format(self.interfaces)]
        if self.detect is not None:
            msg += ['\tDetect: {}'.format(self.detect)]
        if self.nstats['npath'] > 0:
            npath = self.nstats['npath']
            nacc = self.nstats.get('ACC', 0)
            msg += ['\tNumber of paths stored: {}'.format(npath)]
            msg += ['\tNumber of accepted paths: {}'.format(nacc)]
            ratio = float(nacc) / float(npath)
            msg += ['\tRatio accepted/total paths: {}'.format(ratio)]
        return '\n'.join(msg)


def create_path_ensembles(interfaces, include_zero=False):
    """Create a set of `PathEnsemble` objects give position of interfaces.

    This method will create and return a set of objects representing
    path ensembles for a given set of interfaces. This is usefull when
    setting up for instance RETIS simulations. Here we assume that
    the given interfaces define the path ensembles as follows:
    ``[0^-] | [0^+] | [1^+] | ... | [(n-1)^+] | state B``,
    where ``|`` is the specified interface locations in ``interfaces``.
    We assume that to the left of ``interfaces[0]`` we have the reactant
    state and that to the right of ``interfaces[-1]`` we have the product
    state. Given ``n`` interfaces we generate ``n`` or ``n-1`` path ensembles,
    depending on if we want to include [0^-] or not.

    Parameters
    ----------
    interfaces : list of floats
        `interfaces[i]` separates the [(i-1)^+] and [i^+] interfaces.
    include_zero : boolean
        If `include_zero` is True, we include path ensemble [0^-].

    Returns
    -------
    ensembles : list of objects like `PathEnsemble`.
        The generated (empty) path ensemble objects.
    detect : list of floats
        These are interfaces that can be used for an analysis,
        i.e. for detection and matching of probabilities.
    """
    detect = []
    ensembles = []
    reactant = interfaces[0]
    product = interfaces[-1]
    if include_zero:
        ensemble_name = '[0^-]'
        interface = [-float('inf'), reactant, reactant]
        path_ensemble = PathEnsemble(ensemble_name, interface,
                                     detect=None)
        ensembles.append(path_ensemble)
    for i, middle in enumerate(interfaces[:-1]):
        interface = [reactant, middle, product]
        try:
            detect.append(interfaces[i+1])
        except IndexError:
            detect.append(product)
        ensemble_name = '[{}^+]'.format(i)
        path_ensemble = PathEnsemble(ensemble_name, interface,
                                     detect=detect[-1])
        ensembles.append(path_ensemble)
    return ensembles, detect
