.PHONY:	
	clean
 
clean:
	find -name \*.pyc -delete
	find -name \*.pyo -delete
	find -name __pycache__ -delete
	find -name \out.rst* -delete
	find -name \*_0* -delete
	find -name \*.restart* -delete
	find -name \*.log* -delete
	-rm -rf 1D-double-well/retis/0*
	-rm -rf gromacs-hydrate/0*
	find -name \*.tpr -delete
	find -name \pyretis.mdp -delete
