.PHONY:	
	    clean
 
clean:
	find -name \*.pyc -delete
	find -name \*.pyo -delete
	find -name __pycache__ -delete
	find -name \*.txt -delete
	find -name \out.rst* -delete
	find -name \*.restart -delete
	find -name \rnd.state -delete
	find -name \*.log* -delete
	find -name \mdout.mdp -delete
	find -name \*.tpr -delete
	rm -rf run-20/0*
	rm -rf run-100/0*
	rm -rf run-restart/0*
	rm -rf gromacs_input/pyretis.mdp
    
