.PHONY:	
	clean
 
clean:
	find -name \*.pyc -delete
	find -name \*.pyo -delete
	find -name __pycache__ -delete
	find -name EXIT -delete
	find -name \*.txt -delete
	find -name out.rst\* -delete
	find -name \*.restart -delete
	find -name \*.state -delete
	find -name \*.log* -delete
	find -name mdout.mdp -delete
	find -name \*.tpr -delete
	-rm -rf run-5/0*
	-rm -rf run-10/0*
	-rm -rf run-restart/0*
	-rm -rf gromacs_input/conf.gro
	-rm -rf gromacs_input/pyretis.mdp
    
