# -*- coding: utf-8 -*-
# Copyright (c) 2015, pyretis Development Team.
# Distributed under the GPLV3 License. See LICENSE for more info.
"""Version information for pyretis.

This file is generated by pyretis (``setup.py``)
"""
short_version = '0.2.0.dev0'
version = '0.2.0.dev0'
full_version = '0.2.0.dev0'
git_revision = 'c092829efc4afec318df2c4499d6351836d8d94c'
git_version = '0.2.0.dev0+c092829'
release = False

if not release:
    version = git_version
