# -*- coding: utf-8 -*-
# Copyright (c) 2019, PyRETIS Development Team.
# Distributed under the LGPLv2.1+ License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '2.0.0'
VERSION = '2.0.0'
FULL_VERSION = '2.0.0'
GIT_REVISION = '28f9181282eb0b1a3f6142cbd94d66f062c8f780'
GIT_VERSION = '2.0.0'
RELEASE = True

if not RELEASE:
    VERSION = GIT_VERSION
