# -*- coding: utf-8 -*-
# Copyright (c) 2015, PyRETIS Development Team.
# Distributed under the LGPLv3 License. See LICENSE for more info.
"""Version information for PyRETIS.

This file is generated by PyRETIS (``setup_version.py``)
"""
SHORT_VERSION = '0.9.1.dev0'
VERSION = '0.9.1.dev0'
FULL_VERSION = '0.9.1.dev0'
GIT_REVISION = '246155f6a29a272014b53aff373dd1de8ddfaf17'
GIT_VERSION = '0.9.1.dev0+246155f'
RELEASE = False

if not RELEASE:
    VERSION = GIT_VERSION
