.PHONY:	
	clean
 
clean:
	find -name \*.pyc -delete
	find -name \*.pyo -delete
	find -name __pycache__ -delete
	find -name EXIT -delete
	find -name \*.txt -delete
	find -name out.rst\* -delete
	find -name \*.restart -delete
	find -name \*.state -delete
	find -name \*.log\* -delete
	find -name mdout.mdp -delete
	find -name \*.tpr -delete
	-rm -rf run-2/0*
	-rm -rf run-10/0*
	-rm -rf run-load/0*
	-rm -rf run-load/initial_path
	-rm -rf merged
	-rm -rf gromacs_input/pyretis.mdp
    
