.PHONY:	
	clean
 
clean:
	rm -rf run-10/001
	rm -rf run-10-20/001
	rm -rf run-full/001
	rm -rf run-full/report
	find -name \*.pyc -delete
	find -name \*.pyo -delete
	find -name __pycache__ -delete
	find -name \*.txt -delete
	find -name \out.rs* -delete
	find -name \*.restart -delete
	find -name \*.log* -delete
