.PHONY:
	clean

clean:
	find -name \*.pyc -delete
	find -name \*.pyo -delete
	find -name __pycache__ -delete
	find -name EXIT -delete
	find -name out.rst\* -delete
	find -name \*.restart -delete
	find -name rnd.state -delete
	find -name \*.log -delete
	find -name mdout.mdp -delete
	find -name \*.tpr -delete
	find -name pyretis.log\* -delete
	-rm -rf pippo/0*
	-rm -rf pippo/*txt
	-rm -rf 0*